exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("contacts")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("contacts").insert([
        {
          name: "Parrnell Livens",
          address: "5152 Marcy Court",
          email: "plivens0@mail.ru",
          mobile: "940-436-4554",
          created_by: 1,
        },
        {
          name: "Alejandra Clemencon",
          address: "1741 Dryden Place",
          email: "aclemencon1@goodreads.com",
          mobile: "229-808-3982",
          created_by: 1,
        },
        {
          name: "Carola Ricciardo",
          address: "591 Golf Course Lane",
          email: "cricciardo2@gmpg.org",
          mobile: "995-413-4183",
          created_by: 1,
        },
        {
          name: "Hendrik Silverson",
          address: "4 Kenwood Point",
          email: "hsilverson3@cmu.edu",
          mobile: "314-272-6050",
          created_by: 1,
        },
        {
          name: "Tris Poston",
          address: "964 Cardinal Drive",
          email: "tposton4@ed.gov",
          mobile: "346-237-1119",
          created_by: 1,
        },
        {
          name: "Kailey Hatt",
          address: "0904 Meadow Ridge Plaza",
          email: "khatt5@apache.org",
          mobile: "651-778-3156",
          created_by: 1,
        },
        {
          name: "Blaire Paty",
          address: "455 4th Terrace",
          email: "bpaty6@google.com.hk",
          mobile: "808-917-9914",
          created_by: 1,
        },
        {
          name: "Dev Alanbrooke",
          address: "7828 Warrior Crossing",
          email: "dalanbrooke7@barnesandnoble.com",
          mobile: "793-258-7806",
          created_by: 1,
        },
        {
          name: "Northrup Simnor",
          address: "443 Village Park",
          email: "nsimnor8@symantec.com",
          mobile: "409-289-1869",
          created_by: 1,
        },
        {
          name: "Patti Setchell",
          address: "56143 Bunker Hill Pass",
          email: "psetchell9@angelfire.com",
          mobile: "709-433-2461",
          created_by: 1,
        },
        {
          name: "Afton Riby",
          address: "4 Independence Park",
          email: "aribya@twitpic.com",
          mobile: "954-149-2036",
          created_by: 1,
        },
        {
          name: "Cord Jiricka",
          address: "3471 Towne Trail",
          email: "cjirickab@yahoo.co.jp",
          mobile: "552-323-5889",
          created_by: 1,
        },
        {
          name: "Gradey MacGuffog",
          address: "1824 Rigney Pass",
          email: "gmacguffogc@tmall.com",
          mobile: "473-562-1143",
          created_by: 1,
        },
        {
          name: "Babb Burhouse",
          address: "3899 Fuller Pass",
          email: "bburhoused@hexun.com",
          mobile: "586-572-8728",
          created_by: 1,
        },
        {
          name: "Corney Andreassen",
          address: "095 Nelson Junction",
          email: "candreassene@addthis.com",
          mobile: "260-195-5171",
          created_by: 1,
        },
        {
          name: "Marnia Grugerr",
          address: "75031 Sutherland Alley",
          email: "mgrugerrf@aboutads.info",
          mobile: "167-644-7751",
          created_by: 1,
        },
        {
          name: "Madelle Parlett",
          address: "2981 Bultman Pass",
          email: "mparlettg@cocolog-nifty.com",
          mobile: "355-303-0786",
          created_by: 1,
        },
        {
          name: "Dianemarie Myford",
          address: "25637 Bowman Circle",
          email: "dmyfordh@hibu.com",
          mobile: "141-792-7431",
          created_by: 1,
        },
        {
          name: "Delores Redholls",
          address: "68 Mitchell Avenue",
          email: "dredhollsi@nps.gov",
          mobile: "935-226-0868",
          created_by: 1,
        },
        {
          name: "Sosanna Oyley",
          address: "13036 Sunfield Avenue",
          email: "soyleyj@over-blog.com",
          mobile: "405-802-5751",
          created_by: 1,
        },
        {
          name: "Tait Hentzeler",
          address: "64297 Wayridge Crossing",
          email: "thentzelerk@devhub.com",
          mobile: "361-589-0651",
          created_by: 1,
        },
        {
          name: "Ham Mewis",
          address: "67 Porter Alley",
          email: "hmewisl@github.io",
          mobile: "935-555-4725",
          created_by: 1,
        },
        {
          name: "Jessica Dalligan",
          address: "3526 Green Parkway",
          email: "jdalliganm@wikispaces.com",
          mobile: "209-708-6560",
          created_by: 1,
        },
        {
          name: "Marcellus Elgey",
          address: "2623 Sauthoff Circle",
          email: "melgeyn@zimbio.com",
          mobile: "197-443-0820",
          created_by: 1,
        },
        {
          name: "Evaleen Mussetti",
          address: "4 Vera Trail",
          email: "emussettio@newyorker.com",
          mobile: "290-287-6381",
          created_by: 1,
        },
        {
          name: "Izak Smee",
          address: "80033 Red Cloud Road",
          email: "ismeep@csmonitor.com",
          mobile: "786-429-5310",
          created_by: 1,
        },
        {
          name: "Damaris Beddo",
          address: "377 8th Hill",
          email: "dbeddoq@bbb.org",
          mobile: "973-719-0079",
          created_by: 1,
        },
        {
          name: "Pamelina Blasoni",
          address: "2 Forster Terrace",
          email: "pblasonir@weibo.com",
          mobile: "439-273-4618",
          created_by: 1,
        },
        {
          name: "Priscilla Francesc",
          address: "57 Sunnyside Terrace",
          email: "pfrancescs@google.ru",
          mobile: "417-339-4102",
          created_by: 1,
        },
        {
          name: "Fielding Jopp",
          address: "54274 Corscot Place",
          email: "fjoppt@ocn.ne.jp",
          mobile: "782-909-3978",
          created_by: 1,
        },
        {
          name: "Gal Okeshott",
          address: "86516 Bunting Place",
          email: "gokeshottu@nature.com",
          mobile: "728-781-5505",
          created_by: 1,
        },
        {
          name: "Babara Healy",
          address: "055 Londonderry Center",
          email: "bhealyv@abc.net.au",
          mobile: "718-556-0521",
          created_by: 1,
        },
        {
          name: "Wat Easum",
          address: "8615 Fair Oaks Court",
          email: "weasumw@jugem.jp",
          mobile: "226-188-4973",
          created_by: 1,
        },
        {
          name: "Velma Banks",
          address: "53 Declaration Drive",
          email: "vbanksx@vkontakte.ru",
          mobile: "508-387-9116",
          created_by: 1,
        },
        {
          name: "Tuesday Attkins",
          address: "3367 Caliangt Road",
          email: "tattkinsy@opensource.org",
          mobile: "415-401-1696",
          created_by: 1,
        },
        {
          name: "Caesar Billes",
          address: "0173 Iowa Hill",
          email: "cbillesz@unblog.fr",
          mobile: "435-544-0658",
          created_by: 1,
        },
        {
          name: "Hoebart Moppett",
          address: "5 Carberry Trail",
          email: "hmoppett10@sina.com.cn",
          mobile: "667-748-4402",
          created_by: 1,
        },
        {
          name: "Nedi Mogridge",
          address: "3029 Ramsey Court",
          email: "nmogridge11@cbc.ca",
          mobile: "540-570-6109",
          created_by: 1,
        },
        {
          name: "Gustavus Dumphries",
          address: "4 Anhalt Place",
          email: "gdumphries12@gizmodo.com",
          mobile: "599-976-5117",
          created_by: 1,
        },
        {
          name: "Elmore Pacheco",
          address: "89 Sachs Avenue",
          email: "epacheco13@myspace.com",
          mobile: "323-149-0960",
          created_by: 1,
        },
        {
          name: "Adeline Pidgeon",
          address: "00093 Havey Park",
          email: "apidgeon14@1und1.de",
          mobile: "987-994-5574",
          created_by: 1,
        },
        {
          name: "Sutton Myatt",
          address: "495 Spohn Parkway",
          email: "smyatt15@craigslist.org",
          mobile: "810-895-7894",
          created_by: 1,
        },
        {
          name: "Osbourn Beckey",
          address: "4 Sherman Point",
          email: "obeckey16@archive.org",
          mobile: "259-197-6676",
          created_by: 1,
        },
        {
          name: "Yorke Favela",
          address: "70445 Mendota Parkway",
          email: "yfavela17@sciencedirect.com",
          mobile: "226-269-3943",
          created_by: 1,
        },
        {
          name: "Leyla Brimmacombe",
          address: "9650 Katie Pass",
          email: "lbrimmacombe18@livejournal.com",
          mobile: "883-524-2086",
          created_by: 1,
        },
        {
          name: "Yurik Klehyn",
          address: "99 Oak Valley Drive",
          email: "yklehyn19@timesonline.co.uk",
          mobile: "450-770-3266",
          created_by: 1,
        },
        {
          name: "Fleur Large",
          address: "707 Carioca Hill",
          email: "flarge1a@moonfruit.com",
          mobile: "497-967-3303",
          created_by: 1,
        },
        {
          name: "Edvard Weeke",
          address: "46987 Dunning Junction",
          email: "eweeke1b@sbwire.com",
          mobile: "144-219-5337",
          created_by: 1,
        },
        {
          name: "Turner Pindell",
          address: "50109 Bartelt Pass",
          email: "tpindell1c@bloglovin.com",
          mobile: "107-255-7647",
          created_by: 1,
        },
        {
          name: "Farah Ordelt",
          address: "6 Ohio Street",
          email: "fordelt1d@meetup.com",
          mobile: "796-839-4987",
          created_by: 1,
        },
        {
          name: "Ranna Capponeer",
          address: "55878 Milwaukee Point",
          email: "rcapponeer1e@skype.com",
          mobile: "191-155-1846",
          created_by: 1,
        },
        {
          name: "Jarib Brownell",
          address: "3 Barby Terrace",
          email: "jbrownell1f@google.de",
          mobile: "793-882-3358",
          created_by: 1,
        },
        {
          name: "Errick McNamee",
          address: "47 Mandrake Lane",
          email: "emcnamee1g@examiner.com",
          mobile: "961-517-6146",
          created_by: 1,
        },
        {
          name: "Meredith Blasiak",
          address: "216 Menomonie Terrace",
          email: "mblasiak1h@bbb.org",
          mobile: "374-687-3104",
          created_by: 1,
        },
        {
          name: "Gusella Grunbaum",
          address: "62300 Lerdahl Crossing",
          email: "ggrunbaum1i@goo.ne.jp",
          mobile: "126-934-9458",
          created_by: 1,
        },
        {
          name: "Cody Barlie",
          address: "648 Warrior Trail",
          email: "cbarlie1j@oaic.gov.au",
          mobile: "174-799-4901",
          created_by: 1,
        },
        {
          name: "Adelbert Backwell",
          address: "99 Hooker Junction",
          email: "abackwell1k@berkeley.edu",
          mobile: "467-457-7983",
          created_by: 1,
        },
        {
          name: "Gabrielle Abatelli",
          address: "51 Basil Plaza",
          email: "gabatelli1l@umich.edu",
          mobile: "377-891-4105",
          created_by: 1,
        },
        {
          name: "Aguistin MacMurray",
          address: "520 Esker Point",
          email: "amacmurray1m@huffingtonpost.com",
          mobile: "503-587-9765",
          created_by: 1,
        },
        {
          name: "Monte Rilton",
          address: "07 Briar Crest Trail",
          email: "mrilton1n@globo.com",
          mobile: "115-687-4882",
          created_by: 1,
        },
        {
          name: "Rudolfo Sneller",
          address: "2 Messerschmidt Avenue",
          email: "rsneller1o@sphinn.com",
          mobile: "212-268-8938",
          created_by: 1,
        },
        {
          name: "Ailis Scola",
          address: "1 Pierstorff Trail",
          email: "ascola1p@nasa.gov",
          mobile: "322-751-1640",
          created_by: 1,
        },
        {
          name: "Wilma Kirsop",
          address: "6 Parkside Lane",
          email: "wkirsop1q@fema.gov",
          mobile: "857-775-3127",
          created_by: 1,
        },
        {
          name: "Pierce McCrohon",
          address: "5 Farwell Alley",
          email: "pmccrohon1r@blogspot.com",
          mobile: "525-381-1357",
          created_by: 1,
        },
        {
          name: "Aubrette O'Duggan",
          address: "4530 Eagle Crest Circle",
          email: "aoduggan1s@4shared.com",
          mobile: "664-683-1385",
          created_by: 1,
        },
        {
          name: "Nesta Le Brun",
          address: "7 Clove Court",
          email: "nle1t@dailymail.co.uk",
          mobile: "488-427-7782",
          created_by: 1,
        },
        {
          name: "Hayward Flexman",
          address: "536 Rutledge Drive",
          email: "hflexman1u@ucoz.com",
          mobile: "267-269-8626",
          created_by: 1,
        },
        {
          name: "Robinia Wadeson",
          address: "18953 Crest Line Drive",
          email: "rwadeson1v@xinhuanet.com",
          mobile: "931-757-6010",
          created_by: 1,
        },
        {
          name: "Dannie Maplethorp",
          address: "606 Lake View Junction",
          email: "dmaplethorp1w@ft.com",
          mobile: "854-983-1263",
          created_by: 1,
        },
        {
          name: "Delmor Herrieven",
          address: "302 Mesta Drive",
          email: "dherrieven1x@163.com",
          mobile: "711-555-8501",
          created_by: 1,
        },
        {
          name: "Murdock Van Merwe",
          address: "271 Reindahl Place",
          email: "mvan1y@nyu.edu",
          mobile: "892-625-4167",
          created_by: 1,
        },
        {
          name: "Charlean Eginton",
          address: "558 Ohio Court",
          email: "ceginton1z@t.co",
          mobile: "717-672-7590",
          created_by: 1,
        },
        {
          name: "Joey Humes",
          address: "9 Fairfield Court",
          email: "jhumes20@squidoo.com",
          mobile: "159-296-9727",
          created_by: 1,
        },
        {
          name: "Ginni Grimster",
          address: "9257 Mcguire Street",
          email: "ggrimster21@tiny.cc",
          mobile: "968-349-2968",
          created_by: 1,
        },
        {
          name: "Corri Ianizzi",
          address: "1 Armistice Hill",
          email: "cianizzi22@exblog.jp",
          mobile: "528-745-5698",
          created_by: 1,
        },
        {
          name: "Westbrooke Matuszkiewicz",
          address: "7915 Mendota Trail",
          email: "wmatuszkiewicz23@xing.com",
          mobile: "326-441-4228",
          created_by: 1,
        },
        {
          name: "Skipp Bartczak",
          address: "893 Veith Junction",
          email: "sbartczak24@flickr.com",
          mobile: "839-845-1974",
          created_by: 1,
        },
        {
          name: "Lynette Golborne",
          address: "8953 Florence Crossing",
          email: "lgolborne25@va.gov",
          mobile: "963-599-3139",
          created_by: 1,
        },
        {
          name: "Rriocard Caroli",
          address: "3 Talisman Way",
          email: "rcaroli26@boston.com",
          mobile: "301-516-1316",
          created_by: 1,
        },
        {
          name: "Saloma Cranham",
          address: "24 Summer Ridge Plaza",
          email: "scranham27@oakley.com",
          mobile: "954-683-8741",
          created_by: 1,
        },
        {
          name: "Clementine Arger",
          address: "03 Kingsford Road",
          email: "carger28@xinhuanet.com",
          mobile: "253-614-3686",
          created_by: 1,
        },
        {
          name: "Lesley Davidovitch",
          address: "3 Darwin Avenue",
          email: "ldavidovitch29@redcross.org",
          mobile: "970-515-0926",
          created_by: 1,
        },
        {
          name: "Lewiss Finnick",
          address: "72 Atwood Drive",
          email: "lfinnick2a@shop-pro.jp",
          mobile: "393-314-4470",
          created_by: 1,
        },
        {
          name: "Tonnie Bisley",
          address: "8 Crescent Oaks Circle",
          email: "tbisley2b@typepad.com",
          mobile: "565-696-0326",
          created_by: 1,
        },
        {
          name: "Vere Fraczek",
          address: "5054 Bowman Pass",
          email: "vfraczek2c@de.vu",
          mobile: "856-521-1240",
          created_by: 1,
        },
        {
          name: "Nessie Pitblado",
          address: "98 1st Junction",
          email: "npitblado2d@reddit.com",
          mobile: "459-770-5160",
          created_by: 1,
        },
        {
          name: "Parsifal Caddies",
          address: "970 Gulseth Drive",
          email: "pcaddies2e@cbc.ca",
          mobile: "367-599-6669",
          created_by: 1,
        },
        {
          name: "Russ Orrocks",
          address: "619 Vahlen Circle",
          email: "rorrocks2f@zimbio.com",
          mobile: "347-208-9076",
          created_by: 1,
        },
        {
          name: "Martin Mew",
          address: "4895 Mallard Drive",
          email: "mmew2g@yellowpages.com",
          mobile: "998-495-9396",
          created_by: 1,
        },
        {
          name: "Penrod Rosensaft",
          address: "1857 Larry Park",
          email: "prosensaft2h@imdb.com",
          mobile: "986-364-4044",
          created_by: 1,
        },
        {
          name: "Anthiathia Roskam",
          address: "49920 Dakota Way",
          email: "aroskam2i@fema.gov",
          mobile: "843-335-6276",
          created_by: 1,
        },
        {
          name: "Normie Murton",
          address: "619 Anderson Place",
          email: "nmurton2j@bigcartel.com",
          mobile: "902-434-6612",
          created_by: 1,
        },
        {
          name: "Lion Campey",
          address: "14 Lien Circle",
          email: "lcampey2k@virginia.edu",
          mobile: "739-703-2066",
          created_by: 1,
        },
        {
          name: "Bealle Bedow",
          address: "38 Roxbury Trail",
          email: "bbedow2l@ucsd.edu",
          mobile: "201-318-1774",
          created_by: 1,
        },
        {
          name: "Wileen De Gogay",
          address: "94 Grover Center",
          email: "wde2m@cloudflare.com",
          mobile: "465-122-7588",
          created_by: 1,
        },
        {
          name: "Clerc Cordelette",
          address: "47 Melvin Court",
          email: "ccordelette2n@telegraph.co.uk",
          mobile: "689-899-2505",
          created_by: 1,
        },
        {
          name: "Barret Balducci",
          address: "129 Melvin Pass",
          email: "bbalducci2o@dion.ne.jp",
          mobile: "625-466-3334",
          created_by: 1,
        },
        {
          name: "Ezri McCaskill",
          address: "960 Hauk Circle",
          email: "emccaskill2p@sciencedirect.com",
          mobile: "681-466-2698",
          created_by: 1,
        },
        {
          name: "Arney State",
          address: "1690 Marquette Plaza",
          email: "astate2q@drupal.org",
          mobile: "346-480-5219",
          created_by: 1,
        },
        {
          name: "Tory Coweuppe",
          address: "54537 Brown Street",
          email: "tcoweuppe2r@mtv.com",
          mobile: "391-809-4724",
          created_by: 1,
        },
      ]);
    });
};
